feat(angular): use Ionic standalone components
ionic-team/starters pull request #1798
Opened 2023-09-07 19:01 UTC by thetaPC

2023-09-15 17:42 UTC, mapsandapps requested changes
I saw a couple things you did that differed from the [guide](https://ionic-docs-git-4612-docs-ionic1.vercel.app/docs/angular/build-options#using-ionic-standalone-components-in-standalone-based-applications).

As well as the other comments, it looks like

```
              {
                "glob": "**/*.svg",
                "input": "node_modules/ionicons/dist/ionicons/svg",
                "output": "./svg"
              }
```

needs to be removed from the angular.json (twice in the same file).

2023-09-15 17:42 UTC, mapsandapps commented on angular-standalone/base/src/main.ts
> +import { IonicRouteStrategy } from '@ionic/angular/common';
I think this can also come from `@ionic/angular/standalone`?

2023-09-15 17:42 UTC, mapsandapps commented on angular-standalone/official/list/src/app/home/home.page.ts
> +import { RefresherCustomEvent } from '@ionic/angular';
I think this can also come from `@ionic/angular/standalone`?

2023-09-15 17:42 UTC, mapsandapps commented on angular-standalone/official/list/src/app/message/message.component.ts
> +import { Platform } from '@ionic/angular/common';
These Platform imports can come from `@ionic/angular/standalone`

2023-09-15 21:03 UTC, thetaPC commented on angular-standalone/official/list/src/app/view-message/view-message.page.ts
> +addIcons({ personCircle });
I'm not sure, I was following the design doc. I'll switch to follow the Framework docs to stick with consistency.

2023-09-18 17:14 UTC, mapsandapps approved these changes
looks good 👍🏻

2023-10-12 18:31 UTC, thetaPC commented
@mapsandapps I updated the versions and would like a double check that everything still works.

2023-10-12 18:46 UTC, sean-perkins approved these changes
Tested the blank starter locally and the dependency updates look good from the latest commit.

2023-10-12 19:38 UTC, mapsandapps approved these changes

2023-10-12 19:57 UTC, merged